# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pda0004.github.io/DS-teams-project1/"

git_url = "https://github.com/pda0004/DS-teams-project1/tree/main/"

def custom_doc_links(name): return None
